language: ruby
rbenv:
- 2.7.2
addons:
  postgresql: 9.6
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: VJ/cHbokGa0N3DgMBoJA3oc5/wdP1QH2WUkvFk7uyP69h/bAuIRRI2H+7CPNjHHNx9zpIFTH/Kd3tKcQV+GbwhayDdEzg9Y415Kym8J/2rE+vycIZUatGX1B1KTxCxYTbt7Aee5eGxdOHmCCU3K0/uD4VoaVaqzov3sEZ9/lgLcKXvsB9QQzXqHYCe9sUJaq7GqFSHHmhaGEDhpTMvnYrqNV7cA6RgQk6TuvbQQKqME5NzDy1hirHIj32Q1R+6tfEnWol9aS1zOhW6DDXnLC9rP0kLqKF4PSCq2xo/PI8I8VdNmA3MroZJ9VwwYMCkgY2QGegU+F2C/EQUs8xV9SSFheIhqm2mDkV17DX4MhQiVjrT/bb2whAqSQ4K9KDJc5bQTgk+nFRQOQtWRqDpdLk56sq09HYiUeLArnAcpTJMLxa0VBZuHCPSmI3v6YDUbrd8gKwYlRZ3SstNGh36z1qxFMocSg3xbdSF6u7euQNMdkmMCQI8WmL7+kdHPCQGJGK+2ko9zew2Kd/O8NpLIGCuDSd/ZJGYr6CUj/dfgMEykJW8HKgwIbYflcKn2JPo49EivvoS8KYlZ+ltFVC8XTDCbGacHkfuB/FgGSF2F5didDJHv+mgxFeB5pzRLLW87neTu8iRvtChnRnK3Wa3e0spfiL8PcjAZCMaAus5JiKqc=
  app: choreganize-api
  on:
    repo: choreorganize/choreganize-api
    branch: main
  skip_cleanup: 'true'
